# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stbq4\Desktop\python\Notebook3\chap06\06_03\Pityna\qt_PitynaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ListWidgetLog = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidgetLog.setGeometry(QtCore.QRect(5, 0, 340, 500))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.ListWidgetLog.setFont(font)
        self.ListWidgetLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ListWidgetLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ListWidgetLog.setObjectName("ListWidgetLog")
        self.RadioButton_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButton_1.setGeometry(QtCore.QRect(30, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.RadioButton_1.setFont(font)
        self.RadioButton_1.setChecked(True)
        self.RadioButton_1.setObjectName("RadioButton_1")
        self.RadioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButton_2.setGeometry(QtCore.QRect(240, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.RadioButton_2.setFont(font)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit.setGeometry(QtCore.QRect(5, 540, 680, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.LineEdit.setFont(font)
        self.LineEdit.setObjectName("LineEdit")
        self.LabelShowImg = QtWidgets.QLabel(self.centralwidget)
        self.LabelShowImg.setGeometry(QtCore.QRect(350, 0, 500, 300))
        self.LabelShowImg.setText("")
        self.LabelShowImg.setPixmap(QtGui.QPixmap(":/re/img/talk.gif"))
        self.LabelShowImg.setObjectName("LabelShowImg")
        self.ButtonTalk = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTalk.setGeometry(QtCore.QRect(690, 540, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ButtonTalk.setFont(font)
        self.ButtonTalk.setObjectName("ButtonTalk")
        self.LabelResponce = QtWidgets.QTextEdit(self.centralwidget)
        self.LabelResponce.setGeometry(QtCore.QRect(350, 300, 500, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LabelResponce.setFont(font)
        self.LabelResponce.setObjectName("LabelResponce")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuClose = QtWidgets.QAction(MainWindow)
        self.menuClose.setObjectName("menuClose")
        self.menu.addAction(self.menuClose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.ButtonTalk.clicked.connect(MainWindow.button_talk_slot) # type: ignore
        self.RadioButton_1.clicked.connect(MainWindow.show_responder_name) # type: ignore
        self.RadioButton_2.clicked.connect(MainWindow.hidden_responder_name) # type: ignore
        self.menuClose.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RadioButton_1.setText(_translate("MainWindow", "Responderを表示"))
        self.RadioButton_2.setText(_translate("MainWindow", "Responderを非表示"))
        self.ButtonTalk.setText(_translate("MainWindow", "話す"))
        self.menu.setTitle(_translate("MainWindow", "ファイル"))
        self.menuClose.setText(_translate("MainWindow", "shut"))
import qt_resource_rc
